### ISSUE TITLE
How fast will different computers prove their work?

### ISSUE THREAD

**Issue by sjud** [sebadob/spow#6]
Hi,
I have some questions about this crate. How does this effect user experience for users with different quality computers? If I'm sending my app to a 2015 android vs a m3 mac or something how much will this effect the users?

**Comment by sebadob** [comment]
There is no easy answer to this - it depends.

The idea of a Proof of Work (PoW) is, that bots and spammers need to sacrifice some compute resources, so they cannot spam like crazy. This means, that if you request something like that, the amount of work must always be the same, more or less, independent from the clients capabilities. Because otherwise a spammer could just mimic a device from 2010 and would get reduced work requests, which defeats the whole idea of it.

What I would suggest is the following:
- Deploy a minimal version of it. You could take the [leptos-captcha-example](https://github.com/sebadob/leptos-captcha/tree/main/examples/axum-example) and just modify the Frontend slightly, so you would execute 100 calculations with a single press of a button.
- Take the device with the lowest specs that you want to support "nicely" (which is very subjective again)
- Do a few tests with this very old device and adjust the difficulty for the PoW, until you are happy with the result.

Just keep in mind, that more modern devices will handle the task much faster, and so would bots and spammers. This is not a complete protection against any bots. If they actually are willing to do calculate the PoW, they can do this. It is not like "robots cannot solve captcha puzzles". The idea of this crate is that it is just too expensive for them to actually calculate the work, while a normal user would mostly not even care. Most of these algorithms either just don't try again if they get any non OK answer from the backend, or they have short timeouts, when they actually would run a headless browser (with WASM and JS enabled), which means they would simply not go on with the calculation.

I am using this crate in a few of my own projects and never had issues again so far.  
The biggest impact has the WASM binary. If you can support WASM on each of these older devices, this will get you a huge head start against all other Javascript PoWs out there. If you on the other hand have a Rust mobile app, you can use the crate directly which is even faster than WASM in the browser, of course.

Just fyi, when you do some tests with the difficulty, make sure you do a few of them. I would suggest like doing 100 automated calculations with requesting a whole new PoW each time. The algorithm works in a way, that you may get very lucky and do minimal work, or you get a hard one and may need to compute more.  It is really the same behavior  as it is in crypto currencies. So, do like 100 tests with a given difficulty and fetch a new PoW each time and take a look at the median time taken.

In any case, even if the older device has to wait for instance let's say for 5 seconds, the UX is way better than if you would request the user to solve a typical captcha, which even humans have to do multiple times and takes way longer to solve. That's my opinion on these. As long as you show to your user, that the request is being validated, it should be fine.

Another thing you could do is to request PoW with different difficulties depending on the action. For instance, request higher difficulties for logging in or doing a registration, but smaller ones for less important tasks.

**Comment by sjud** [comment]
Wow! Thanks for this very thorough response. You're right, I should just test it! Thanks for pointing me in the right direction. :)
